---
title: "evi_dist_comp_occ_length_plantseason"
author: "Natalie Ayers"
date: "`r Sys.Date()`"
output: pdf_document
---

First, run the code in format_combined_data_for_analysis.R to get the dataframes used in this analysis. (sorry this is a bad way to do this..)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(gridExtra)
library(grid)
library(broom)
library(sp)
library(dplyr)
```

```{r occ length datasets}
occlen_extremes_relig <- plant_timing_data |>
                     filter(!is.na(isis_occ_status)) |>
                     mutate(sunni_status=ifelse(sunni_dom==1,'Sunni Dominated',
                             ifelse(sunni_mix==1,'Sunni Mixed',
                                    ifelse(no_sunni==1,'No Sunni Pop',
                                           NA))),
                            occ_len_cat = ifelse(occ_length_mon<=12, "Short",
                                                 ifelse(occ_length_mon>=35,"Long",
                                                        "Mid"))) |>
                     mutate(occlen_and_relig = paste0(sunni_status," - ",occ_len_cat),
                            occlen_and_timing = paste0(occ_len_cat, " - " ,isis_occ_status))

occlen_extremes_relig_filt <- occlen_extremes_relig |>
                                filter(occ_len_cat %in% c('Long','Short')) |>
                                filter(isis_occ_status %in% c('Pre','Post'))


occ_vs_noocc_relig <- plant_timing_data |>
                       mutate(sunni_status=ifelse(sunni_dom==1,'Sunni Dominated',
                               ifelse(sunni_mix==1,'Sunni Mixed',
                                      ifelse(no_sunni==1,'No Sunni Pop',
                                             NA))),,
                              occ_len_cat = ifelse(!is.na(isis_occ_status),
                                                  ifelse(occ_length_mon<=12, "Short",
                                                 ifelse(occ_length_mon>=35,"Long",
                                                        "Mid")),NA),
                              occ_status = ifelse(!is.na(isis_occ_status), "Occupied",
                                                          "Not Occupied"),
                              isis_presence = ifelse(is.na(isis_occ_status),
                                                     ifelse(year_num <= 2013, 'Pre',
                                                      ifelse(year_num >= 2018, 'Post',
                                                     ifelse((year_num > 2013 & year_num < 2018), 'During',NA
                                                           ))),isis_occ_status)) |>
                       mutate(occ_and_relig = paste0(sunni_status," - ",occ_status),
                              occ_and_timing = paste0(occ_status, " - " ,isis_presence))


occ_vs_noocc_relig_filt <- occ_vs_noocc_relig |>
                            filter(isis_presence %in% c('Pre','Post'))

```

## Compare Occupation Lengths : Long vs Short

```{r compare mean evi dists occ length}
plt_occ_len_wheatbarley <- ggplot(filter(occlen_extremes_relig_filt,
                                   plant_season=='WheatBarley'),
                            aes(x=mean_evi_scaled,color=occlen_and_timing)) + 
                      geom_density() + 
                      scale_color_manual(values=c("#F02015","#FA900F","#f5ed02",
                                                  "#030ffc","#0cbff5","#0cf5a3")) + 
                      labs(title="Mean EVI for ISIS Occupied Areas by Occupation Length and Timing during Wheat and Barley Growing Months",
                           x = "Mean EVI", y="Density", color="ISIS Occupation Length - Timing") + 
                      theme_bw() 
plt_occ_len_summer <- ggplot(filter(occlen_extremes_relig_filt,
                                   plant_season=='SummerCrops'),
                            aes(x=mean_evi_scaled,color=occlen_and_timing)) + 
                      geom_density() + 
                      scale_color_manual(values=c("#F02015","#FA900F","#f5ed02",
                                                  "#030ffc","#0cbff5","#0cf5a3")) + 
                      labs(title="Mean Summer EVI for ISIS Occupied Areas by Occupation Length and Timing",
                           x = "Mean EVI", y="Density", color="ISIS Occupation Length - Timing") + 
                      theme_bw() 

fin_plots <- arrangeGrob(plt_occ_len_wheatbarley,plt_occ_len_summer,nrow=1,
             bottom=textGrob("ISIS Occupation Years Collected Manually based on IOM Occupation Reports; Long Occupation is >= 35 months, Short Occupation is <= 12 months; Wheat and Barley Growing Season is Dec - Apr, Summer is May - Sept"))


img_file <- './data/data_visualizations/mean_plant_season_evi_dists_occlen.png'
ggsave(img_file,fin_plots, width=24, height=10, dpi=400)
```

```{r compare mean resid evi dists occ length}
plt_resid_occ_len_wheatbarley <- ggplot(filter(occlen_extremes_relig_filt,
                                   plant_season=='WheatBarley'),
                            aes(x=mean_evi_resids,color=occlen_and_timing)) + 
                      geom_density() + 
                      scale_color_manual(values=c("#F02015","#FA900F",
                                                  "#030ffc","#05f5ed")) + 
                      labs(title="Mean EVI Residuals for ISIS Occupied Areas by Occupation Length and Timing during Wheat and Barley Growing Months",
                           x = "Mean EVI Resids", y="Density", color="ISIS Occupation Length - Timing") + 
                      theme_bw() 
plt_resid_occ_len_summer <- ggplot(filter(occlen_extremes_relig_filt,
                                   plant_season=='SummerCrops'),
                            aes(x=mean_evi_resids,color=occlen_and_timing)) + 
                      geom_density() + 
                      scale_color_manual(values=c("#F02015","#FA900F",
                                                  "#030ffc","#05f5ed")) + 
                      labs(title="Mean Summer EVI Residuals for ISIS Occupied Areas by Occupation Length and Timing",
                           x = "Mean EVI Resids", y="Density", color="ISIS Occupation Length - Timing") + 
                      theme_bw() 

fin_plots <- arrangeGrob(plt_resid_occ_len_wheatbarley,plt_resid_occ_len_summer,nrow=1,
             bottom=textGrob("ISIS Occupation Years Collected Manually based on IOM Occupation Reports; Long Occupation is >= 35 months, Short Occupation is <= 12 months; Wheat and Barley Growing Season is Dec - Apr, Summer is May - Sept"))


img_file <- './data/data_visualizations/mean_plant_season_evi_resid_dists_occlen.png'
ggsave(img_file,fin_plots, width=24, height=10, dpi=400)

```


```{r compare max resid evi dists occ length}
plt_max_resid_occ_len_wheatbarley <- ggplot(filter(occlen_extremes_relig_filt,
                                   plant_season=='WheatBarley'),
                            aes(x=max_evi_resids,color=occlen_and_timing)) + 
                      geom_density() + 
                      scale_color_manual(values=c("#F02015","#FA900F",
                                                  "#030ffc","#05f5ed")) + 
                      labs(title="Max EVI Residuals for ISIS Occupied Areas by Occupation Length and Timing during Wheat and Barley Growing Months",
                           x = "Max EVI Resids", y="Density", color="ISIS Occupation Length - Timing") + 
                      theme_bw() 
plt_max_resid_occ_len_summer <- ggplot(filter(occlen_extremes_relig_filt,
                                   plant_season=='SummerCrops'),
                            aes(x=max_evi_resids,color=occlen_and_timing)) + 
                      geom_density() + 
                      scale_color_manual(values=c("#F02015","#FA900F",
                                                  "#030ffc","#05f5ed")) + 
                      labs(title="Max Summer EVI Residuals for ISIS Occupied Areas by Occupation Length and Timing",
                           x = "Max EVI Resids", y="Density", color="ISIS Occupation Length - Timing") + 
                      theme_bw() 

fin_plots <- arrangeGrob(plt_max_resid_occ_len_wheatbarley,plt_max_resid_occ_len_summer,nrow=1,
             bottom=textGrob("ISIS Occupation Years Collected Manually based on IOM Occupation Reports; Long Occupation is >= 35 months, Short Occupation is <= 12 months; Wheat and Barley Growing Season is Dec - Apr, Summer is May - Sept"))


img_file <- './data/data_visualizations/max_plant_season_evi_resid_dists_occlen.png'
ggsave(img_file,fin_plots, width=24, height=10, dpi=400)

```


```{r compare max resid evi dists occ length}
plt_max_occ_len_wheatbarley <- ggplot(filter(occlen_extremes_relig_filt,
                                   plant_season=='WheatBarley'),
                            aes(x=max_evi_scaled,color=occlen_and_timing)) + 
                      geom_density() + 
                      scale_color_manual(values=c("#F02015","#FA900F",
                                                  "#030ffc","#05f5ed")) + 
                      labs(title="Max EVI for ISIS Occupied Areas by Occupation Length and Timing during Wheat and Barley Growing Months",
                           x = "Max EVI", y="Density", color="ISIS Occupation Length - Timing") + 
                      theme_bw() 

plt_max_occ_len_summer <- ggplot(filter(occlen_extremes_relig_filt,
                                   plant_season=='SummerCrops'),
                            aes(x=max_evi_scaled,color=occlen_and_timing)) + 
                      geom_density() + 
                      scale_color_manual(values=c("#F02015","#FA900F",
                                                  "#030ffc","#05f5ed")) + 
                      labs(title="Max Summer EVI for ISIS Occupied Areas by Occupation Length and Timing",
                           x = "Max EVI", y="Density", color="ISIS Occupation Length - Timing") + 
                      theme_bw() 


fin_plots <- arrangeGrob(plt_max_occ_len_wheatbarley,plt_max_occ_len_summer,nrow=1,
             bottom=textGrob("ISIS Occupation Years Collected Manually based on IOM Occupation Reports; Long Occupation is >= 35 months, Short Occupation is <= 12 months; Wheat and Barley Growing Season is Dec - Apr, Summer is May - Sept"))


img_file <- './data/data_visualizations/max_plant_season_evi_dists_occlen.png'
ggsave(img_file,fin_plots, width=24, height=10, dpi=400)
```

## Compare Occupation vs No Occupation

```{r compare max resid evi dists occ noocc}
plt_max_resid_occ_noocc_wheatbarley <- ggplot(filter(occ_vs_noocc_relig_filt,
                                   plant_season=='WheatBarley'),
                            aes(x=max_evi_resids,color=occ_and_timing)) + 
                      geom_density() + 
                      scale_color_manual(values=c("#F02015","#FA900F",
                                                  "#030ffc","#05f5ed")) + 
                      labs(title="Max EVI Residuals for Areas by ISIS Occupation and Timing during Wheat and Barley Growing Months",
                           x = "Max EVI Resids", y="Density", color="ISIS Occupation - Timing") + 
                      theme_bw() 
plt_max_resid_occ_noocc_summer <- ggplot(filter(occ_vs_noocc_relig_filt,
                                   plant_season=='SummerCrops'),
                            aes(x=max_evi_resids,color=occ_and_timing)) + 
                      geom_density() + 
                      scale_color_manual(values=c("#F02015","#FA900F",
                                                  "#030ffc","#05f5ed")) + 
                      labs(title="Max Summer EVI Residuals for Areas by ISIS Occupation and Timing",
                           x = "Max EVI Resids", y="Density", color="ISIS Occupation - Timing") + 
                      theme_bw() 

fin_plots <- arrangeGrob(plt_max_resid_occ_noocc_wheatbarley,plt_max_resid_occ_noocc_summer,nrow=1,
             bottom=textGrob("ISIS Occupation Years Collected Manually based on IOM Occupation Reports; For non-occupied areas, Pre-ISIS time is 2001-2013, Post-ISIS time is 2018-2022; Wheat and Barley Growing Season is Dec - Apr, Summer is May - Sept"))


img_file <- './data/data_visualizations/max_plant_season_evi_resid_dists_occ_noocc.png'
ggsave(img_file,fin_plots, width=24, height=10, dpi=400)
```

```{r compare mean resid evi dists occ length}
plt_resid_occ_noocc_wheatbarley <- ggplot(filter(occ_vs_noocc_relig_filt,
                                   plant_season=='WheatBarley'),
                            aes(x=mean_evi_resids,color=occ_and_timing)) + 
                      geom_density() + 
                      scale_color_manual(values=c("#F02015","#FA900F",
                                                  "#030ffc","#05f5ed")) + 
                      labs(title="Mean EVI Residuals for Areas by ISIS Occupation and Timing during Wheat and Barley Growing Months",
                           x = "Mean EVI Resids", y="Density", color="ISIS Occupation - Timing") + 
                      theme_bw() 
plt_resid_occ_noocc_summer <- ggplot(filter(occ_vs_noocc_relig_filt,
                                   plant_season=='SummerCrops'),
                            aes(x=mean_evi_resids,color=occ_and_timing)) + 
                      geom_density() + 
                      scale_color_manual(values=c("#F02015","#FA900F",
                                                  "#030ffc","#05f5ed")) + 
                      labs(title="Mean Summer EVI Residuals for Areas by ISIS Occupation and Timing",
                           x = "Mean EVI Resids", y="Density", color="ISIS Occupation - Timing") + 
                      theme_bw() 

fin_plots <- arrangeGrob(plt_resid_occ_noocc_wheatbarley,plt_resid_occ_noocc_summer,nrow=1,
             bottom=textGrob("ISIS Occupation Years Collected Manually based on IOM Occupation Reports; For non-occupied areas, Pre-ISIS time is 2001-2013, Post-ISIS time is 2018-2022; Wheat and Barley Growing Season is Dec - Apr, Summer is May - Sept"))


img_file <- './data/data_visualizations/mean_plant_season_evi_resid_dists_occ_noocc.png'
ggsave(img_file,fin_plots, width=24, height=10, dpi=400)
```







